---

name: Linter
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Super-Linter
        uses: docker://github/super-linter:latest
        env:
          VALIDATE_JS: true
          DEFAULT_BRANCH: main
